### ISSUE TITLE
Git push is not working in my terminal after cloning lab so cannot submit pull request

### ISSUE THREAD

**Issue by ezaman** [learn-co-curriculum/locationTrivia-objects#9] opened 2016-06-16 17:43 UTC
I used the correct SSH link for this lab: git@github.com:ezaman/locationTrivia-objects-ios-0616.git
However, git push did not allow me to submit a pull request due to the following error:
"Username for 'https://github.com': ezaman
Password for 'https://ezaman@github.com': 
remote: Permission to learn-co-students/locationTrivia-objects-ios-0616.git denied to ezaman.
fatal: unable to access 'https://github.com/learn-co-students/locationTrivia-objects-ios-0616.git/': The requested URL returned error: 403"

Please advise as I'm sure my username and password are correct. Thank you!

**Comment by markedwardmurray** [comment] 2016-06-16 19:19
it looks like you're trying to push to the `learn-co-students` repo and not your fork. check your remote with `git remote -v` and if you see `/learn-co-students/` instead of `/ezaman/` just correct it with `git remote set-url` ( https://help.github.com/articles/changing-a-remote-s-url/ )

**Comment by gj** [comment] 2017-07-19 21:04
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂

**Closed as completed by gj** 2017-07-19 21:04 UTC
Labels: Product
